package net.atmos.diagnostics;

public enum DiagnosticEvent {
    STAGE_ENTER,
    STAGE_EXIT,
    CLUSTER_GENERATED,
    COMPOSITION_ACCEPTED,
    COMPOSITION_REJECTED,
    RENDER_CLUSTER_ACCEPTED,
    RENDER_CLUSTER_REJECTED,
    QUAD_GENERATED,
    VERTEX_SUBMITTED,
    STATE_RESET,
    ANOMALY_DETECTED
}